# Generated by Django 3.2.25 on 2024-04-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='friendly_name',
            new_name='friendly_team_name',
        ),
        migrations.RemoveField(
            model_name='team_subs',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team_subs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='team_subs',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='team_subs',
            name='is_sub',
        ),
        migrations.RemoveField(
            model_name='team_subs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team_subs',
            name='price',
        ),
        migrations.AddField(
            model_name='team_subs',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='checkout.order'),
        ),
        migrations.AddField(
            model_name='team_subs',
            name='period',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='team_subs',
            name='player_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='team_subs',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subs.team'),
        ),
    ]
