# Generated by Django 3.2.25 on 2024-04-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0002_auto_20240412_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_subs',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='subs.team'),
        ),
    ]
