# Generated by Django 3.2.25 on 2024-04-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0003_alter_team_subs_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_subs',
            name='product',
        ),
    ]
