# Generated by Django 3.2.25 on 2024-04-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0004_remove_team_subs_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_subs',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
