# Generated by Django 3.2.25 on 2024-04-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20240413_1420'),
        ('clubadmin', '0004_player_display_name'),
        ('subs', '0006_auto_20240418_1150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_subs',
            new_name='TeamSubs',
        ),
    ]
