# Generated by Django 3.2.25 on 2024-04-18 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubadmin', '0004_player_display_name'),
        ('subs', '0007_rename_team_subs_teamsubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsubs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsubs',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamsubs',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='teamsubs',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='clubadmin.team'),
        ),
    ]
