# Generated by Django 3.2.25 on 2024-04-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0009_alter_product_id'),
        ('subs', '0008_auto_20240418_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsubs',
            name='product',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='kit.product'),
        ),
    ]
