# Generated by Django 3.2.25 on 2024-04-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0009_alter_product_id'),
        ('subs', '0010_alter_teamsubs_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsubs',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='kit.product'),
        ),
    ]
