# Generated by Django 3.2.25 on 2024-04-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20240419_1622'),
        ('kit', '0009_alter_product_id'),
        ('subs', '0011_alter_teamsubs_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsubs',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='teamsubs',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='kit.product'),
        ),
    ]
