# Generated by Django 3.2.25 on 2024-04-19 12:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('opponent', models.CharField(max_length=50)),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)])),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
