# Generated by Django 3.2.25 on 2024-04-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='time',
            field=models.CharField(default='3pm', max_length=50),
            preserve_default=False,
        ),
    ]
