# Generated by Django 3.2.25 on 2024-04-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_category',
            options={'verbose_name_plural': 'News Categories'},
        ),
    ]
