# Generated by Django 3.2.25 on 2024-04-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0004_team_team_subs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team_subs',
            options={'verbose_name_plural': 'Team Subs'},
        ),
    ]
