# Generated by Django 3.2.25 on 2024-04-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0005_alter_team_subs_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_subs',
            name='product',
        ),
        migrations.RemoveField(
            model_name='team_subs',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Team_subs',
        ),
    ]
