# Generated by Django 3.2.25 on 2024-04-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubadmin', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='display_name',
            field=models.CharField(default='display name', max_length=50),
        ),
    ]
