# Generated by Django 3.2.25 on 2024-04-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubadmin', '0004_player_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='display_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
